dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- '3.10'
services:
  - mysql
env:
  - MYSQL_HOST="127.0.0.1"
  - MYSQL_PASSWORD=""
install:
- pip install poetry
script: make test
after_success:
- codecov
