site_name: Danio
theme:
  name: material
repo_name: strongbugman/danio
repo_url: https://github.com/strongbugman/danio
edit_uri: ""

nav:
  - Introduction: 'index.md'
  - Model Definition: 'model_definition.md'
  - Make Queries: 'make_queries.md'
  - Model Signal: 'model_signal.md'
  - Bulk Queries: 'bulk_queries.md'
  - Combo Queries: 'combo_queries.md'
  - Model Migration: 'model_migration.md'
  - SQL Injection: 'sql_injection.md'
  - Custom Field: 'custom_field.md'
  - PostgreSQL: 'postgresql.md'
  - SQLite: 'sqlite.md'
  - Tips: 'tips.md'
